name: "custom_model"
platform: "pytorch_libtorch"
default_model_filename: "model.pt"

input: [
    {
        name: "INPUT__0"
        data_type: TYPE_FP32
        dims: [ 640, 640, 3 ]
    }
]

output: [
    {
        name: "OUTPUT__0"
        data_type: TYPE_FP32
        dims: [ 640, 640, 3 ]
    }
]

instance_group: [
    {
        count: 1
        kind: KIND_GPU
    }
]