name: "face_detection_script_scrfd_10g"
platform: "pytorch_libtorch"
default_model_filename: "script_scrfd.ts"

input: [
    {
        name: "INPUT__0"
        data_type: TYPE_FP16
        dims: [ -1, 640, 640, 3 ]
    }
]

output: [
    {
        name: "OUTPUT__0"
        data_type: TYPE_FP16
        dims: [ -1, -1, 15 ]
    }
]

instance_group: [
    {
        count: 1
        kind: KIND_GPU
    }
]

parameters: {
    key: "INFERENCE_MODE"
        value: {
            string_value:"true"
        }
    }

# parameters: {
#     key: "DISABLE_OPTIMIZED_EXECUTION"
#         value: {
#             string_value: "true"
#         }
# }