name: "face_detection_script_scrfd_10g_batch"
platform: "pytorch_libtorch"
default_model_filename: "script_scrfd_torch25_batch.ts"
max_batch_size: 8
input: [
    {
        name: "INPUT__0"
        data_type: TYPE_FP16
        dims: [ 640, 640, 3 ]
    },
    {
        name: "INPUT__1"
        data_type: TYPE_FP16
        dims: [ 1 ]
    },
    {
        name: "INPUT__2"
        data_type: TYPE_FP16
        dims: [ 1 ]
    }
]

output: [
    {
        name: "OUTPUT__0"
        data_type: TYPE_FP16
        dims: [ -1, 15 ]
    }
]

instance_group: [
    {
        count: 1
        kind: KIND_GPU
    }
]

parameters: {
    key: "INFERENCE_MODE"
        value: {
            string_value:"true"
        }
    }
parameters: {
  key: "DISABLE_OPTIMIZED_EXECUTION"
      value: {
      string_value: "true"
      }
}

optimization {
  input_pinned_memory {
    enable: true
  }
  output_pinned_memory {
    enable: true
  }
}

model_warmup [
    {
        name: "Single sample"
        batch_size: 1
        inputs: {
            key: "INPUT__0"
            value: {
                data_type: TYPE_FP16
                dims: [ 640, 640, 3]
                random_data: true
            }
        }
        inputs: {
            key: "INPUT__1"
            value: {
                data_type: TYPE_FP16
                dims: [ 1]
                random_data: true
            }
        }
        inputs: {
            key: "INPUT__2"
            value: {
                data_type: TYPE_FP16
                dims: [ 1]
                random_data: true
            }
        }
    },
    {
        name: "batch sample"
        batch_size: 2
        inputs: {
            key: "INPUT__0"
            value: {
                data_type: TYPE_FP16
                dims: [ 640, 640, 3]
                random_data: true
            }
        }
        inputs: {
            key: "INPUT__1"
            value: {
                data_type: TYPE_FP16
                dims: [ 1]
                random_data: true
            }
        }
        inputs: {
            key: "INPUT__2"
            value: {
                data_type: TYPE_FP16
                dims: [ 1]
                random_data: true
            }
        }
    }
]

version_policy: {
  specific: {
    versions: [1]
  }
}
